### ISSUE TITLE
Support Sites from StackExchange Network

### ISSUE THREAD

**Issue by jonathan-scholbach** [dracula/stackoverflow#4]
It would be nice if the theme provided support for the other sites in the StackExchange network. I created a PR for this: https://github.com/dracula/stackoverflow/pull/3

**Comment by jonathan-scholbach** [comment]
@wasi-master @zenorocha - Just trying to make you aware of this PR.

**Comment by wasi-master** [comment]
@jonathan-scholbach Thanks, I am just wondering about the theme name now

**Comment by wasi-master** [comment]
@jonathan-scholbach Thanks
