### ISSUE TITLE
Links within inline code snippets is unreadable

### ISSUE THREAD

**Issue by asportnoy** [dracula/stackoverflow#5]
Links within inline codeblocks are very hard to read. It didn't use to be this way so I'm guessing some SO update messed it up.
![Screenshot 2023-10-20 at 10 57 06](https://github.com/dracula/stackoverflow/assets/14863373/531dcc0a-69c7-4a7f-8937-a1ff328c32ca)

Markdown:
```
[`display text`](URL)
```

**Comment by wasi-master** [comment]
![image](https://github.com/dracula/stackoverflow/assets/63045920/91e09ce9-ea9c-41ce-98db-534af9ddafef)
looks fine to me 🤔

**Comment by wasi-master** [comment]
Oh this is because you've set your accent color to comment
